version: 2
updates:
  # Update dependencies for Client using NPM.
  - package-ecosystem: "npm"
    directory: "/client"
    target-branch: develop
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[npm] bump: "
      include: "scope"
    reviewers:
      - "jordi-jaspers"
    versioning-strategy: increase
    version-update:
      ignore:
        - dependency-name: "*"
          update-types: ["version-update:semver-major"]
    security-updates:
      pull-requests: true
    groups:
      all:
        patterns:
          - "*"

  # Update dependencies for Server using Gradle.
  - package-ecosystem: "gradle"
    directory: "/server"
    target-branch: develop
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[spring] bump: "
      include: "scope"
    reviewers:
      - "jordi-jaspers"
    version-update:
      ignore:
        - dependency-name: "*"
          update-types: ["version-update:semver-major"]
    security-updates:
      pull-requests: true
    groups:
      all:
        patterns:
          - "*"
