version: 2
updates:
  # Client (SvelteKit + Bun) dependencies
  - package-ecosystem: "npm"
    directory: "/client"
    target-branch: "develop"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Brussels"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "jordi-jaspers"
    versioning-strategy: "auto"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    version-update:
      ignore:
        - dependency-name: "*"
          update-types: ["version-update:semver-major"]
    post-update:
      commands:
        - ".github/scripts/update-bun-lockfile.sh"
    groups:
      all:
        patterns:
          - "*"

  # Server (Spring Boot) dependencies
  - package-ecosystem: "gradle"
    directory: "/server"
    target-branch: "develop"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Brussels"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "jordi-jaspers"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    version-update:
      ignore:
        - dependency-name: "*"
          update-types: ["version-update:semver-major"]
    groups:
      all:
        patterns:
          - "*"
