networks:
  internal:
    name: internal

services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb-ha:pg17
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "5432:5432"
    environment:
      TZ: Europe/Amsterdam
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - timescaledb_data:/var/lib/postgresql/data  # Persistent data storage for TimescaleDB.

  inbucket:
    container_name: inbucket
    image: inbucket/inbucket:latest
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "9000:9000"  # Web UI port.
      - "2500:2500"  # SMTP service port (correct port mapping).
      - "1100:1100"  # POP3 service port.
    volumes:
      - inbucket_data:/data  # Persistent storage for Inbucket's data.

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistent storage for RabbitMQ data

volumes:
  timescaledb_data:  # Volume for TimescaleDB
  inbucket_data:     # Volume for Inbucket
  rabbitmq_data:     # Volume for RabbitMQ
