name: Cleanup Reports

on:
  workflow_dispatch:  # Manual trigger
  
permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Clean up old runs
        run: |
          # Function to recreate branch index
          create_branch_index() {
            local branch_path="$1"
            local branch_name=$(basename "$branch_path")
          
            # Calculate relative path back to root
            local back_path=""
            local depth=$(echo "$branch_path" | tr -cd '/' | wc -c)
            for ((i=0; i<=depth; i++)); do
              back_path="../$back_path"
            done
          
            cat > "$branch_path/index.html" << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <title>Build Reports - $branch_name branch</title>
            <style>
              /* ... copy styles from your existing branch index ... */
            </style>
          </head>
          <body>
          <div class="container">
            <a class="back-link" href="${back_path}reports/">Back to all branches</a>
            <h1>Build Reports - ${branch_name} branch</h1>
            <div class="builds-grid">
            </div>
          </div>
          </body>
          </html>
          EOF
          }

          cd reports

          # Delete all merge request directories
          find . -type d -path "*/refs/pull/*" -exec rm -rf {} +

          # For remaining branches, remove all run directories but keep branch structure
          find . -mindepth 1 -maxdepth 1 -type d | while read branch; do
            if [ -d "$branch" ]; then
              # Remove all run directories
              find "$branch" -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} +
              # Recreate empty branch index
              create_branch_index "$branch"
            fi
          done

          # Recreate main index
          cat > index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <title>Build Reports - All Branches</title>
            <style>
              /* ... copy styles from your existing main index ... */
            </style>
          </head>
          <body>
          <div class="container">
            <h1>Build Reports - All Branches</h1>
            <div class="branches-grid">
              $(for branch in $(find . -mindepth 1 -maxdepth 1 -type d); do
                branch_name=$(basename "$branch")
                echo "<p class=\"branch-item\"><a href=\"$branch_name/\" class=\"branch-link\">$branch_name</a></p>"
              done)
            </div>
          </div>
          </body>
          </html>
          EOF

      - name: Commit changes
        run: |
          git add .
          git commit -m "Cleanup old runs and merge request directories" || echo "No changes to commit"
          git push origin gh-pages
