name: Cleanup Reports

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight every Sunday

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main for scripts
        uses: actions/checkout@v4
        with:
          path: main-branch

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Make cleanup script executable
        run: chmod +x main-branch/.github/scripts/cleanup-reports.sh

      - name: Run cleanup
        working-directory: gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          ../main-branch/.github/scripts/cleanup-reports.sh
          
          # Commit and push changes
          git add .
          git commit -m "Cleanup old runs and inactive branch directories" || echo "No changes to commit"
          git push origin gh-pages

      - name: Print completion message
        run: echo "::notice title=🧹 Cleanup completed::Reports have been cleaned up successfully"
