name: CI Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master, develop ]

jobs:
  client-quality-check:
    uses: ./.github/workflows/client-quality-check.yml

  client-build-artifacts:
    needs: client-quality-check
    uses: ./.github/workflows/client-build-artifacts.yml

  server-quality-check:
    uses: ./.github/workflows/server-quality-check.yml

  server-build-artifacts:
    needs: server-quality-check
    uses: ./.github/workflows/server-build-artifacts.yml

  server-publish-report:
    needs: server-build-artifacts
    uses: ./.github/workflows/server-publish-report.yml
