name: Run Integration Tests & Build Artifacts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
  pull_request:
    branches: [ master, develop ]

jobs:
  build-client:
    name: Build the Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun version manager
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Build project
        run: bun install --frozen-lockfile && bun run build

  build-server:
    name: Build the Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
      TESTCONTAINERS_RYUK_DISABLED: true

    services:
      docker:
        image: docker:20.10.24
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            server/*.gradle*
            server/**/gradle-wrapper.properties

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon --stacktrace
