name: Publish Server Report

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-report:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Download Quality Report
        uses: actions/download-artifact@v4
        with:
          name: server-quality-report-${{ github.sha }}
          path: artifact/quality

      - name: Download Test Report
        uses: actions/download-artifact@v4
        with:
          name: server-test-report-${{ github.sha }}
          path: artifact/tests
        continue-on-error: true  # In case build step didn't run

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: artifact

      - name: Print deployment URL
        run: |
          echo "📊 Report deployed to: ${{ steps.deployment.outputs.page_url }}"
