name: Publish Server Report

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-report:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Get build information
        id: build_info
        run: |
          echo "timestamp=$(date +%Y-%m-%d_%H-%M-%S)" >> $GITHUB_OUTPUT
          echo "run_id=${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 1
        continue-on-error: true

      - name: Create reports directory
        run: |
          mkdir -p reports
          if [ -d "gh-pages" ]; then
            cp -r gh-pages/* reports/ || true
          fi

      - name: Download Quality Report
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: server-quality-report
          path: reports/${{ steps.build_info.outputs.run_id }}/quality
        continue-on-error: true

      - name: Download Test Report
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: server-test-report
          path: reports/${{ steps.build_info.outputs.run_id }}/tests
        continue-on-error: true

      - name: Make scripts executable
        run: |
          chmod +x .github/scripts/create-indexes.sh
          chmod +x .github/scripts/create-main-indexes.sh

      - name: Create indexes
        run: |
          .github/scripts/create-indexes.sh "${{ steps.build_info.outputs.run_id }}"
          .github/scripts/create-main-indexes.sh "${{ steps.build_info.outputs.run_id }}"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Print deployment URL
        if: success() && steps.deployment.outputs.page_url != ''
        run: |
          echo "::notice title=📊 Report URL::${{ steps.deployment.outputs.page_url }}${{ steps.build_info.outputs.run_id }}"
