name: Build Server Artifacts & Run Tests

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-server:
    name: Build the Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'
      TESTCONTAINERS_RYUK_DISABLED: true
      TESTCONTAINER_DOCKER_NETWORK: integration-testcontainers
      GRADLE_OPTS: "-Xmx4g -Xms1g -Dorg.gradle.daemon=false"

    outputs:
      has_reports: ${{ steps.check_reports.outputs.has_reports }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21 Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            server/*.gradle*
            server/**/gradle-wrapper.properties      

      - name: Docker network setup
        run: |
          docker network create ${{ env.TESTCONTAINER_DOCKER_NETWORK }} || true
          docker network ls
          docker info
          docker ps

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon --parallel --stacktrace
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
          TC_DAEMON: true
          TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
          TESTCONTAINERS_CHECKS_DISABLE: true

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: server-build-artifacts-${{ github.sha }}
          path: |
            ./server/build/libs
          retention-days: 7
          if-no-files-found: error

      - name: Check for reports
        id: check_reports
        run: |
          if [ -d "./build/reports" ]; then
            echo "has_reports=true" >> $GITHUB_OUTPUT
          else
            echo "has_reports=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload reports
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: server-build-report-${{ github.sha }}
          path: ./server/build/reports
          retention-days: 7
