name: Check Server Code Quality

on:
  workflow_call:
  workflow_dispatch:

jobs:
  backend-quality:
    name: Backend Quality Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            server/*.gradle*
            server/**/gradle-wrapper.properties

      - name: Run Quality Checks
        run: ./gradlew spotlessCheck checkQualityMain

      - name: Check Quality report Availability
        id: check_reports
        run: |
          if [ -d "./build/reports" ]; then
            echo "has_reports=true" >> $GITHUB_OUTPUT
          else
            echo "has_reports=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload Quality report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: server-quality-report-${{ github.sha }}
          path: ./server/build/reports
          retention-days: 7
