name: Publish Server Report

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-report:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Get build information
        id: build_info
        run: |
          echo "timestamp=$(date +%Y-%m-%d_%H-%M-%S)" >> $GITHUB_OUTPUT
          echo "run_id=${{ github.run_id }}" >> $GITHUB_OUTPUT

      # New steps to preserve existing content
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 1
        continue-on-error: true

      - name: Create reports directory
        run: |
          mkdir -p reports
          if [ -d "gh-pages" ]; then
            cp -r gh-pages/* reports/ || true
          fi

      # Download and organize new reports
      - name: Download Quality Report
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: server-quality-report
          path: reports/${{ steps.build_info.outputs.run_id }}/quality
        continue-on-error: true

      - name: Download Test Report
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: server-test-report
          path: reports/${{ steps.build_info.outputs.run_id }}/tests
        continue-on-error: true

      # Create an index for this build
      - name: Create build index
        run: |
          mkdir -p reports/${{ steps.build_info.outputs.run_id }}
          cat > reports/${{ steps.build_info.outputs.run_id }}/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <title>Build Report - Run ${{ steps.build_info.outputs.run_id }}</title>
          </head>
          <body>
            <h1>Build Report - Run ${{ steps.build_info.outputs.run_id }}</h1>
            <h2>Reports:</h2>
            <ul>
              <li><a href="quality/">Quality Reports</a></li>
              <li><a href="tests/">Test Reports</a></li>
            </ul>
            <p><a href="../">Back to all reports</a></p>
          </body>
          </html>
          EOF

      # Create main index if it doesn't exist
      - name: Create main index
        run: |
          cat > reports/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <title>Build Reports</title>
          </head>
          <body>
            <h1>Build Reports</h1>
            <h2>Latest Build:</h2>
            <p><a href="${{ steps.build_info.outputs.run_id }}/">Run ${{ steps.build_info.outputs.run_id }}</a></p>
          </body>
          </html>
          EOF

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Print deployment URL
        if: success() && steps.deployment.outputs.page_url != ''
        run: |
          echo "::notice title=📊 Report URL::${{ steps.deployment.outputs.page_url }}${{ steps.build_info.outputs.run_id }}"
